BSPInvoiceBundle_invoice:
    pattern:  /invoice/{id}
    defaults: { _controller: BSPInvoiceBundle:Invoice:view }

BSPInvoiceBundle_pdf:
    pattern:  /invoice/pdf/{id}
    defaults: { _controller: BSPInvoiceBundle:Invoice:getPDF }
