bsp_invoice_invoice:
    pattern:  /invoice/{id}
    defaults: { _controller: BSPInvoiceBundle:Invoice:view }

bsp_invoice_pdf:
    pattern:  /invoice/pdf/{id}
    defaults: { _controller: BSPInvoiceBundle:Invoice:getPDF }
