parameters:    
    # Invoice Manipulator
    bsp_invoice.manipulator.class: BSP\InvoiceBundle\Util\InvoiceManipulator

services:
    # Invoice Manipulator
    bsp_invoice.manipulator:
        class: %bsp_invoice.manipulator.class%
        arguments:
            - @bsp_invoice.invoice_manager
